# Generated by Django 4.2 on 2023-08-03 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_person_cpassword_person_email_person_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='cPassword',
            new_name='Conform_Password',
        ),
    ]
