# Generated by Django 4.2 on 2023-08-03 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_rename_cpassword_person_conform_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Conform_Password',
        ),
    ]
