# Generated by Django 4.2 on 2023-08-03 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_remove_person_conform_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='password',
            new_name='pwd',
        ),
    ]
