# Generated by Django 4.2 on 2023-08-03 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_rename_password_person_pwd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='pwd',
            new_name='password',
        ),
    ]
